name: Allure Integration
  
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cypress dependencies
        run: npm install
        
      - name: Cypress run with Cucumber
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          command: npm run cypress:execution-allure          
               
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Get Allure history
        uses: peaceiris/actions-allure-history@v2
        if: always()
        with:
          allure_report_dir: allure-results
          allure_history_dir: allure-history  
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
      
